### ISSUE TITLE
Broken with base-gcc on OpenBSD

### ISSUE THREAD

**Issue by julianaito** [grayed/oicb#1]
Hi Vadim,

oicb is built with `-Werror` and that breaks the build with base-gcc:

```
cc -O2 -pipe -Wall -Werror -DHAVE_PLEDGE -DHAVE_UNVEIL  -MD -MP  -nostdinc -idirafter /usr/include -c oicb.c
cc1: warnings being treated as errors
```
We could either patch away `-Werror` in the port or allow injecting `-Wno-error` at the end of CFLAGS by modifying the Makefile here. In any case it builds fine when removed on powerpc.

Since you're upstream and MAINTAINER at the same time, i prefer to let you decide what to do beforehand :)

(cc @kmosiejczuk)

**Comment by kmosiejczuk** [comment]
For the record, this failed in the build I started last night:
===>  Building for oicb-1.1.1
cc -O2 -pipe -Wall -Werror -DHAVE_PLEDGE -DHAVE_UNVEIL  -MD -MP  -nostdinc -idirafter /usr/include -c oicb.c
cc1: warnings being treated as errors
oicb.c: In function 'main':
oicb.c:1139: warning: 'port' may be used uninitialized in this function
*** Error 1 in /usr/obj/ports/oicb-1.1.1/oicb-1.1.1 (<sys.mk>:87 'oicb.o')
*** Error 1 in net/oicb (/usr/ports/infrastructure/mk/bsd.port.mk:2890 '/usr/obj/ports/oicb-1.1.1/.build_done')
*** Error 1 in net/oicb (/usr/ports/infrastructure/mk/bsd.port.mk:2556 'build')
===> Exiting net/oicb with an error

**Comment by grayed** [comment]
Thank you both, I'm pushing new release right now.
