### ISSUE TITLE
Eventually oicb can't write to log files

### ISSUE THREAD

**Issue by jturner** [grayed/oicb#2]
I leave oicb open in tmux and after a couple days it starts failing to write to it's log files. I have to restart it to re-enable it's ability to write to log files. Any ideas?

`oicb: cannot open /home/james/.oicb/logs/supersecret.server.org/room-secret.log`

**Comment by grayed** [comment]
Yep, there is a file handle leak. To be fixed soon, thanks for the report.

**Comment by grayed** [comment]
fixed in 1.2.3 release.
